package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/GetEvinced/stark-marketplace/engine/internal/validate"
	"github.com/spf13/cobra"
)

// renderAllowlistDoc materializes the canonical Markdown surfacing the two
// allowlists exported by internal/validate. Pure function: same input
// (allowlist slices) → same bytes, so CI's drift gate can diff against the
// committed docs/allowlist.md.
func renderAllowlistDoc() []byte {
	cmds := validate.CommandAllowlist()
	tools := validate.AgentToolAllowlist()

	var b bytes.Buffer
	b.WriteString("# MCP command + agent.tools allowlists\n\n")
	b.WriteString("Auto-generated from `engine/internal/validate/allowlist.go` and `engine/internal/validate/toolsallow.go`. **Do not hand-edit** — run `stark allowlist > docs/allowlist.md` after touching either source file (CI fails closed otherwise).\n\n")

	b.WriteString("Governance: adding an entry requires a CODEOWNERS-gated PR with maintainer + `@aryeh-evinced` approval. See [`SECURITY.md` §2](SECURITY.md).\n\n")

	b.WriteString("## MCP `command` allowlist\n\n")
	b.WriteString("MCP `command` values must be a basename present here. Every entry widens the set of binaries an MCP server may spawn on a developer's machine.\n\n")
	b.WriteString("| Command |\n| --- |\n")
	for _, c := range cmds {
		fmt.Fprintf(&b, "| `%s` |\n", c)
	}

	b.WriteString("\n## `agent.tools` allowlist\n\n")
	b.WriteString("Tool grants on `agent` artifacts are surfaced for install-time consent. Unknown grants emit a `stark validate` warning (not a hard error) so reviewers see them in PR output.\n\n")
	b.WriteString("| Tool |\n| --- |\n")
	for _, t := range tools {
		fmt.Fprintf(&b, "| `%s` |\n", t)
	}

	return b.Bytes()
}

func newAllowlistCmd() *cobra.Command {
	var check string
	cmd := &cobra.Command{
		Use:   "allowlist",
		Short: "Print the MCP command + agent.tools allowlists as Markdown (use --check to gate a committed copy)",
		RunE: func(cmd *cobra.Command, args []string) error {
			want := renderAllowlistDoc()
			if check == "" {
				_, err := os.Stdout.Write(want)
				return err
			}
			got, err := os.ReadFile(check)
			if err != nil {
				return fmt.Errorf("read %s: %w", check, err)
			}
			if !bytes.Equal(got, want) {
				return fmt.Errorf("allowlist doc drift: %s does not match the generated bytes. Run `stark allowlist > %s` and commit", check, check)
			}
			fmt.Printf("OK: %s matches generated allowlist doc\n", check)
			return nil
		},
	}
	cmd.Flags().StringVar(&check, "check", "", "verify the file at this path matches the generated bytes (CI drift gate)")
	return cmd
}
