// Package digest computes the two content hashes the engine relies on (spec §11):
//   - Source: a normalized canonical-source hash used as the version-bump gate,
//     excluding display-only metadata (description/tags/summary) and version.
//   - Output: a hash over generated bytes + adapter target version, used for
//     provenance/install ("re-install recommended" on adapter bumps).
package digest

import (
	"crypto/sha256"
	"encoding/hex"
	"sort"
	"strings"

	"github.com/21StarkCom/stark-bifrost/engine/internal/canonjson"
	"github.com/21StarkCom/stark-bifrost/engine/internal/model"
)

// Source returns the version-bump-gate digest. Only identity, type-specific
// canonical fields, dependency refs, MCP config, and the normalized body
// participate. description/tags/summary/version/maturity/category/homepage are
// display metadata and excluded (spec §11).
func Source(a *model.Artifact) string {
	canonical := map[string]any{
		"name":                     a.Name,
		"type":                     string(a.Type),
		"argument-hint":            a.ArgumentHint,
		"model":                    a.Model,
		"disable-model-invocation": a.DisableModelInvocation,
		"allowed-tools":            sortedCopy(a.AllowedTools),
		"tools":                    sortedCopy(a.Tools),
		"requires":                 requiresKey(a.Requires),
		"runtimes":                 runtimesKey(a.Runtimes),
		"mcp":                      mcpKey(a.MCP),
		"body":                     normalizeBody(a.Body),
	}
	b, _ := canonjson.Marshal(canonical)
	sum := sha256.Sum256(b)
	return "sha256:" + hex.EncodeToString(sum[:])
}

func normalizeBody(s string) string {
	s = strings.ReplaceAll(s, "\r\n", "\n")
	lines := strings.Split(s, "\n")
	for i := range lines {
		lines[i] = strings.TrimRight(lines[i], " \t")
	}
	return strings.TrimRight(strings.Join(lines, "\n"), "\n")
}

func sortedCopy(in []string) []any {
	cp := append([]string(nil), in...)
	sort.Strings(cp)
	out := make([]any, len(cp))
	for i, s := range cp {
		out[i] = s
	}
	return out
}

func runtimesKey(rs []model.Runtime) []any {
	cp := make([]string, len(rs))
	for i, r := range rs {
		cp[i] = string(r)
	}
	sort.Strings(cp)
	out := make([]any, len(cp))
	for i, s := range cp {
		out[i] = s
	}
	return out
}

func requiresKey(reqs []model.Requirement) []any {
	keys := make([]string, len(reqs))
	for i, r := range reqs {
		keys[i] = string(r.Type) + ":" + r.Ref
	}
	sort.Strings(keys)
	out := make([]any, len(keys))
	for i, k := range keys {
		out[i] = k
	}
	return out
}

func mcpKey(m *model.MCPConfig) any {
	if m == nil {
		return nil
	}
	envKeys := make([]string, 0, len(m.Env))
	for k, v := range m.Env {
		envKeys = append(envKeys, k+"="+v.SecretRef)
	}
	sort.Strings(envKeys)
	envOut := make([]any, len(envKeys))
	for i, k := range envKeys {
		envOut[i] = k
	}
	return map[string]any{
		"transport": m.Transport,
		"command":   m.Command,
		"args":      stringsToAny(m.Args),
		"url":       m.URL,
		"env":       envOut,
	}
}

func stringsToAny(in []string) []any {
	out := make([]any, len(in))
	for i, s := range in {
		out[i] = s
	}
	return out
}

// Output hashes a set of generated files plus the adapter target version
// (spec §11, §7.7). The map is hashed in sorted-path order so the result is
// independent of map iteration order.
func Output(files map[string][]byte, adapterVersion string) string {
	paths := make([]string, 0, len(files))
	for p := range files {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	h := sha256.New()
	h.Write([]byte("adapter:" + adapterVersion + "\n"))
	for _, p := range paths {
		h.Write([]byte("path:" + p + "\n"))
		h.Write(files[p])
		h.Write([]byte("\n"))
	}
	return "sha256:" + hex.EncodeToString(h.Sum(nil))
}
